lvim.log.level = "warn"
lvim.format_on_save = false
lvim.colorscheme = "catppuccin-macchiato"
lvim.builtin.alpha.active = true
lvim.builtin.alpha.mode = "dashboard"
lvim.builtin.terminal.active = true
lvim.builtin.nvimtree.setup.view.side = "left"
lvim.builtin.nvimtree.setup.renderer.icons.show.git = false
vim.diagnostic.config({ virtual_text = false })
vim.opt.relativenumber = true
lvim.builtin.bufferline.active = false
vim.opt.showtabline = 0
lvim.builtin.breadcrumbs.active = true
